export const products = [
  {
    id: 1,
    title: "Realme 9 pro",
    description: "black in color",
    price: "18000",
    img: "https://image01.realme.net/general/20220131/1643635150323.png.webp",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 2,
    title: "Apple Macbook Air",
    description: "black in color",
    price: "89000",
    img: "https://cdn1.smartprix.com/rx-iXMsgRkkm-w1200-h1200/XMsgRkkm.jpg",
    quantity: 1,
    category: "laptop",
  },
  
  {
    id: 3,
    title: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 4,
    title: "Iphone 12",
    description: "Best mobile ever",
    price: "90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 5,
    title: "Oppo A31",
    description: "black in color",
    price: "12000",
    img: "https://m.media-amazon.com/images/I/71KCwNV6MuL._SL1500_.jpg",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 6,
    title: "Vivo T1",
    description: "black in color",
    price: "15999",
    img: "https://sathya.in/media/80995/catalog/b194403687afd2212c4cf035d28d8e65.png",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 7,
    title: "Apple mac Air",
    description: "black in color",
    price: "2500",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzzp02FlP70EOyjErZ7jEQgzBeN8FifZ9GKz1wmzPgxBvtzYrgU9xhXwQRmMoeQD-pvz4&usqp=CAU",
    quantity: 1,
    category: "laptop",
  },
  {
    id: 8,
    title: "Iphone 12",
    description: "Best mobile ever",
    price: "90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 9,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 10,
    title: "Hp 15s Ryzen 5",
    description: "black in color",
    price: "40000",
    img: "https://cdn1.smartprix.com/rx-iQKVwv1tK-w1200-h1200/QKVwv1tK.jpg",
    quantity: 1,
    category: "laptop",
  },
  {
    id: 11,
    title: "Samsung M21",
    description: "white in color",
    price: "2300",
    img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
    category: "mobile",
  },
  {
    id: 12,
    title: "Dell Inspiron",
    description: "Black in color",
    price: "53000",
    img: "https://m.media-amazon.com/images/I/51if47n2aPL._AC_SL1000_.jpg",
    quantity: 1,
    category: "laptop",
  },
];
